# Playwright MCP Server - Fly.io Deployment Configuration
#
# This configuration file defines the deployment settings for running the Playwright MCP server on Fly.io.
#
# To deploy this application to Fly.io:
# 1. Ensure you have the Fly CLI installed and are logged in
# 2. Run the following deploy command:
#    fly deploy --local-only --ha=false --smoke-checks=false
#
# Deploy command flags explained:
# --local-only: Builds the Docker image locally instead of on Fly's builders
# --ha=false: Disables high availability (single instance deployment)
# --smoke-checks=false: Skips smoke checks after deployment
#
# For more information about Fly.io deployment options, visit: https://fly.io/docs/

app = "news-summarizer-playwright-mcp"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 2